### ISSUE TITLE
influxdb-neb stream connector: missing metrics

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-stream-connector-scripts#32]
Centreon 10.10.15
OS: CentOS 7.8

We have configured the influxdb-neb stream connector. On InfluxDB we can see metrics for the hosts, but there are missing a lot of metrics like interfaces, discs. At the moment we can see this kind of metrics:
![image](https://user-images.githubusercontent.com/6400595/91564514-08eb3600-e941-11ea-8173-f272ba5a2892.png)

But there are a lot off other metrics that are missing at the moment. Any idea?

We have some error on the stream connector like
```
Fri 28 Aug 2020 03:16:31 PM CEST: ERROR: EventQueue:flush: HTTP POST request FAILED: return code is 400
Fri 28 Aug 2020 03:16:31 PM CEST: ERROR: EventQueue:flush: HTTP POST request FAILED: message line 1 is "{"error":"partial write: invalid field name: input field \"time\" on measurement \"host-latency\" is invalid dropped=204"}
```

**Comment by UrBnW** [comment]
To avoid messing-up the Influx database, the influxdb-neb Stream Connector only handles new-perfdata-style metrics.
You then usually needs to add `--use-new-perfdata` to your checks.
You already have some data in your Influx database because some plugins / modes already enforce this flag by default.

The `partial write` error is interesting.
How does the performance data returned by your hosts' check command looks like ?
And what is this check command ?
I should be able to write a quick fix upon your inputs.

**Comment by joschi99** [comment]
I have done some look on interface commands for example for Palo Alto. I can't find the option `--use-new-perfdata` you mentioned and in our case there are missing completely all interfaces (Palo Alto, Juniper, Linux, ecc.). 

The host check is done by
`$USER1$/check_icmp -H $HOSTADDRESS$ -w 3000.0,80% -c 5000.0,100% -p 1`

Any idea?

**Comment by UrBnW** [comment]
`--use-new-perfdata` is not documented yet.
But `interfaces` mode supports it.
Simply add it to your checks then.

For the `partial write` error, what does `check_icmp -V` returns on your infra ?

**Comment by UrBnW** [comment]
#34 should solve your `partial write` issue.
